---
title: "Hosting on Github"
---

I have chosen to host this site on github, which among other things enables you to use R and R Markdown from within R Studio to produce the content you see here.  Set up was straight forward enough, below are some of the useful things I learned and links I used during set up.

####Useful sites for initial set up

_Configuring your github account and R Studio folders to host your R Markdown as html pages is easy when you know how, the links below should help with that._

Setting up Github and R Studio to host your R Markdown website has loads of tutorials, [here is a good one](http://nickstrayer.me/RMarkdown_Sites_tutorial/ "Hosting on git tutorial") 

Check out [YouTube](https://www.youtube.com/results?search_query=github+hosting+r+markdown) for more useful guides

[R Markdown by R Studio](http://rmarkdown.rstudio.com/rmarkdown_websites.html "R Markdown - R Studio") has some useful examples and commands too 


####Commiting updates to github

_The order of actions required is; save all files, render the site, review and commit changes, push commited changes._

1. rmarkdown::render_site()  
    *Creates an html file from each rmd file in the directory, a _ at the strart of a filename will exclude that file from this process.*

2. Commit this change to github: On the Git menu click Diff and review all changes, then commit.  
    *Note: by default this commits to the master, but as things get more complex it is possible to commit to a branch and then review on github before merging into the master *

3. Push the commited changes to the master (or branch) using the green up arrow.



